# frozen_string_literal: true

module SkinMaker
  class Generator
    TEMPLATE_PATH = File.join(SkinMaker::ROOT, 'themes', '_template.yml')
    BASE_LAYOUTS = %w[material plain bootswatch].freeze

    def scaffold!(name, layout: 'material')
      raise Error, "Invalid layout: #{layout}" unless LAYOUTS.include?(layout)

      theme_path = File.join(SkinMaker::THEMES_DIR, "#{name}.yml")
      raise Error, "Theme already exists: #{theme_path}" if File.exist?(theme_path)

      FileUtils.mkdir_p(SkinMaker::THEMES_DIR)

      template = YAML.load_file(TEMPLATE_PATH)
      template['name'] = name
      template['layout'] = layout

      File.write(theme_path, template.to_yaml)
      generate!(theme_path)
      puts "Created theme: themes/#{name}.yml"
      puts "Created skin:  scss/skins/#{name}.scss"
      puts "Run: bundle exec rake skins:build[#{name}]"
    end

    def generate!(theme_path)
      theme = Theme.new(theme_path)
      skin_path = skin_path_for(theme.name)
      FileUtils.mkdir_p(File.dirname(skin_path))
      File.write(skin_path, render_skin(theme))
      skin_path
    end

    def render_skin(theme)
      colors = theme.colors
      fonts = theme.fonts
      spacing = theme.spacing
      body_font = sass_font_list(fonts['body'] || default_body_font(theme.layout))
      heading_font = sass_font_list(fonts['heading'] || fonts['body'] || default_body_font(theme.layout))
      mono_font = sass_font_list(fonts['mono'] || 'monospace')
      base_import = BASE_LAYOUTS.include?(theme.layout) ? "@use '../base';\n" : ''

      <<~SCSS
        #{base_import}@use '../tokens' with (
          $color-main: #{colors.fetch('main', '#ffffff')},
          $color-primary: #{colors.fetch('primary', '#2196f3')},
          $color-secondary: #{colors.fetch('secondary', '#ba3925')},
          $color-tertiary: #{colors.fetch('tertiary', '#186d7a')},
          $color-sidebar: #{colors.fetch('sidebar', '#0d47a1')},
          $color-link: #{colors.fetch('link', '#90caf9')},
          $color-link-alt: #{colors.fetch('link_alt', '#f44336')},
          $color-link-hover: #{optional_color(colors, 'link_hover')},
          $color-white: #{colors.fetch('white', '#ffffff')},
          $color-black: #{colors.fetch('black', '#000000')},
          $color-text: #{optional_color(colors, 'text')},
          $color-border: #{colors.fetch('border', '#eeeeee')},
          $color-code-bg: #{colors.fetch('code_bg', '#f5f5f5')},
          $color-table-stripe: #{colors.fetch('table_stripe', '#f9f9f9')},
          $color-footer-text: #{optional_color(colors, 'footer_text')},
          $font-body: #{body_font},
          $font-heading: #{heading_font},
          $font-mono: #{mono_font},
          $font-google: '#{fonts.fetch('google', default_google_font(theme.layout))}',
          $header-padding: #{spacing.fetch('header_padding', '25px')},
          $heading-padding: #{spacing.fetch('heading_padding', '10px')},
          $sect-border-radius: #{spacing.fetch('sect_border_radius', '8px')},
          $toc-title-size: #{spacing.fetch('toc_title_size', '16px')},
          $body-margin-x: #{spacing.fetch('body_margin_x', default_body_margin(theme.layout))},
          $body-font-size: #{optional_size(spacing, 'body_font_size')},
          $line-height: #{optional_size(spacing, 'line_height')},
          $content-max-width: #{optional_size(spacing, 'content_max_width')}
        );
        @use '../layout/#{theme.layout}' as layout;

        /* Asciidoctor default stylesheet | MIT License | https://asciidoctor.org */
        /* Generated by skin-maker from themes/#{theme.name}.yml — layout: #{theme.layout} */

        @include tokens.emit-font-import;
        @include tokens.emit-root-tokens;
        @include layout.apply;
      SCSS
    end

    def sass_font_list(value)
      parts = value.to_s.split(',').map { |part| part.strip.delete('"') }
      family = parts.shift
      fallbacks = parts.empty? ? ['sans-serif'] : parts
      "(#{([family] + fallbacks).map { |part| "'#{part}'" }.join(', ')})"
    end

    def optional_color(colors, key)
      value = colors[key]
      return 'null' if value.nil? || value.to_s.empty?

      value
    end

    def optional_size(spacing, key)
      value = spacing[key]
      return 'null' if value.nil? || value.to_s.empty?

      value
    end

    def default_body_font(layout)
      case layout
      when 'tufte' then 'et-book, Palatino, Georgia, serif'
      when 'bootswatch' then 'Helvetica Neue, Helvetica, Arial, sans-serif'
      else 'Noto Sans, sans-serif'
      end
    end

    def default_google_font(layout)
      case layout
      when 'tufte' then 'none'
      when 'bootswatch' then 'Helvetica+Neue'
      else 'Noto+Sans'
      end
    end

    def skin_path_for(name)
      File.join(SkinMaker::SKINS_DIR, "#{name}.scss")
    end

    def default_body_margin(layout)
      layout == 'bootswatch' ? '10%' : '0'
    end
  end
end
